### ISSUE TITLE
Unable to install on fresh 18.04 system with provided script.

### ISSUE THREAD

**Issue by vmnovak** [BookStackApp/devops#16]
Attempts to install the provided ./installation-ubuntu-18.04.sh script fails with multiple errors.

![bookstackerror](https://user-images.githubusercontent.com/29717657/49613674-28c11600-f976-11e8-8b23-bd0a7cf5f4b3.PNG)

I have confirmed I am running installer with Sudo, and that the Universe repository is enabled and updated.

**Comment by ssddanbrown** [comment]
@vmnovak Sorry for my late response, Did you find a solution to this? 
Was your system a clean install or had you tired installing php beforehand in any way?

**Comment by vmnovak** [comment]
Hi Dan,

Sorry I didn’t respond to this sooner. Holidays and all!  Hope yours was well!

It was a clean install  which is why I reached out to you, otherwise I would assume the issue is on my end.  I forget what the issue actually was but it had something to do with one of the upstream libraries on Ubuntu’s side changing names or versions or something and not expecting what the script was.

The bad news is I fixed it and didn’t document it.
The good news is I love your program so I’m going to be redeploying it from my test VM to my actual home network for me to use.  I expect I’ll run into the same snag so I will be sure to document everything and send it to you so you can either tell me I’m crazy or make any adjustments you feel are warranteed.

Thanks for getting back to me, I will try not to take to long in getting this information to you.

Sent from Mail for Windows 10

**Comment by ssddanbrown** [comment]
@vmnovak Happy to hear you got things working. I'll close this for now since you got things going but if you do come across the same issue then just open up an new issue here with the details/fix.
