### ISSUE TITLE
Centos 7 Script

### ISSUE THREAD

**Issue by okwindart** [BookStackApp/devops#21]
I have tried to run this script:
https://github.com/BookStackApp/devops/blob/ca3d5a7294412a58791f6a25d988df0f9704ff93/scripts/installation-CentOS-7.sh

But I am getting the following error:

![image](https://user-images.githubusercontent.com/46505131/66661745-215d3f80-ec0d-11e9-9874-1ddcd0b1d7fb.png)

This is on a clean Centos 7 (minimal install) VM

Thanks!
Ken

**Comment by ssddanbrown** [comment]
Hi @okwindart,
Are you using windows at all in the process of getting the script onto the server? Any transfer, copy or edit steps ran via windows could add such carriage returns that are causing the error.

**Comment by okwindart** [comment]
@ssddanbrown: What's the full wget command to get this script downloaded into the server? Thank you!

**Comment by ssddanbrown** [comment]
@okwindart 

```bash
wget https://raw.githubusercontent.com/BookStackApp/devops/master/scripts/installation-centos-7.sh
```

**Comment by okwindart** [comment]
Thanks! That worked!

BTW: Thank you for developing BookStack. I am simply loving it! I had it installed earlier with Ubuntu but wanted to get it working with Centos. You can now close this issue.

**Comment by ssddanbrown** [comment]
@okwindart Awesome! glad you're enjoying the project!
