### ISSUE TITLE
Doesn't work. Apache fails to start. Fresh Ubuntu Server 20.04.3

### ISSUE THREAD

**Issue by HubKing** [BookStackApp/devops#30]
I used the ready-made virtual OS image ( https://www.osboxes.org/ubuntu-server ) of Ubuntu Server 20.04.3. I downloaded the script and ran. It asked for a domain name, but of course, as a typical home user, I do not have a domain name for my home network, so I just pressed enter. It said the installation is finished, but I could open the page. When I restarted the virtual OS, I could see an error message of Apache failing to start. But I did not do anything, and everything was done by the script. The only potential fault of mine could be not entering a domain name, but if so, why did the script continue?

![image](https://user-images.githubusercontent.com/10900489/134119607-97711fd5-478d-43c1-8450-87b448b0e519.png)

![image](https://user-images.githubusercontent.com/10900489/134119890-4f713aa1-03c0-4fcf-b872-af659721073b.png)

**Comment by ssddanbrown** [comment]
Hi @HubKing,

> It asked for a domain name, but of course, as a typical home user, I do not have a domain name for my home network, so I just pressed enter.

> The only potential fault of mine could be not entering a domain name, but if so, why did the script continue?

This is the issue. BookStack is a web application. Even if used locally it would be accessed via a browser via a domain or IP address. The script requires this and will not stop if none is provided, We don't currently have error checking for someone not providing this.

This can be added after the fact if required, the domain is used in two places:

1. In the `/var/www/bookstack/.env` file. The `APP_URL=` line must be configured to be equal to your base app URL (`APP_URL=http://docs.example.com` for example).
2. In the `/etc/apache2/sites-available/bookstack.conf` file. The line starting `ServerName` must be set to your domain (`ServerName docs.example.com` for example). You'll need to restart apache after this change (`sudo systemctl restart apache2`)

**Comment by ssddanbrown** [comment]
I've now added a check to the Ubuntu20.04 install script to ensure that the lack of a domain stops the script early. 

https://github.com/BookStackApp/devops/blob/152fcff5313c08c7d9137bba9268ee7b4cc81d4d/scripts/installation-ubuntu-20.04.sh#L15-L21

Will therefore close this off.
