### ISSUE TITLE
Server block for Nginx: example for subdirectory instead of root?

### ISSUE THREAD

**Issue by ekianjo** [BookStackApp/devops#32]
Hi, I am wondering if the example you have shared for Nginx server block on:

https://github.com/BookStackApp/devops/blob/main/config/nginx

can be used in the same way for subdirectories on the nginx server? Have you ever tried it?

**Comment by ssddanbrown** [comment]
Hi @ekianjo,
Sorry for my late reply. Yes, you can acheive a subdirectory style (In terms of the URL) setup on Nginx.
I've updated our documentation page to include instructions for nginx:
https://www.bookstackapp.com/docs/admin/subdirectory-setup/#nginx-setup

I've also added an example nginx config for this here:
https://github.com/BookStackApp/devops/blob/main/config/nginx/subpath-proxy-config

Will therefore close this off but just shout if you have any issues using these.
