### ISSUE TITLE
Facing issue in Database migration

### ISSUE THREAD

**Issue by manojvirat457** [BookStackApp/devops#33]
![image](https://user-images.githubusercontent.com/29704113/153544871-3bb112b6-2c3f-4dcc-ba47-35171ac02acc.png)

Please help us in fixing it.

**Comment by lommes** [comment]
What database and Version are you using?

https://laravel-news.com/laravel-5-4-key-too-long-error

**Comment by ssddanbrown** [comment]
Hi @manojvirat457 I'm going to guess you're running WAMP, or similar, and that the database is using the `MyISAM` engine by default. You should instead use the `InnoDB` engine for BookStack database tables.

If any of the above seems incorrect feel free to raise an issue via our [support request form](https://github.com/BookStackApp/BookStack/issues/new?assignees=&labels=%3Adog2%3A+Support&template=support_request.yml&title=%5BSupport+Request%5D%3A+) which would allow you to provide the details required to help us support/debug.
