### ISSUE TITLE
Script fails

### ISSUE THREAD

**Issue by soapster** [BookStackApp/devops#36]
dan@bookstacks:~$ sudo apt update
Hit:1 http://us.archive.ubuntu.com/ubuntu jammy InRelease
Hit:2 http://us.archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:3 http://us.archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:4 http://us.archive.ubuntu.com/ubuntu jammy-security InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
16 packages can be upgraded. Run 'apt list --upgradable' to see them.
dan@bookstacks:~$ sudo ./installation-ubuntu-20.04.sh

Enter the domain you want to host BookStack and press [ENTER]
Examples: my-site.com or docs.my-site.com
bookstacks.local
Adding component(s) 'universe' to all repositories.
Press [ENTER] to continue or Ctrl-c to cancel.
Hit:1 http://us.archive.ubuntu.com/ubuntu jammy InRelease
Hit:2 http://us.archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:3 http://us.archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:4 http://us.archive.ubuntu.com/ubuntu jammy-security InRelease
Reading package lists... Done
Hit:1 http://us.archive.ubuntu.com/ubuntu jammy InRelease
Hit:2 http://us.archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:3 http://us.archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:4 http://us.archive.ubuntu.com/ubuntu jammy-security InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
16 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package php7.4-fpm is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Unable to locate package php7.4
E: Couldn't find any package by glob 'php7.4'
E: Package 'php7.4-fpm' has no installation candidate
E: Unable to locate package php7.4-curl
E: Couldn't find any package by glob 'php7.4-curl'
E: Unable to locate package php7.4-mbstring
E: Couldn't find any package by glob 'php7.4-mbstring'
E: Unable to locate package php7.4-ldap
E: Couldn't find any package by glob 'php7.4-ldap'
E: Unable to locate package php7.4-tidy
E: Couldn't find any package by glob 'php7.4-tidy'
E: Unable to locate package php7.4-xml
E: Couldn't find any package by glob 'php7.4-xml'
E: Unable to locate package php7.4-zip
E: Couldn't find any package by glob 'php7.4-zip'
E: Unable to locate package php7.4-gd
E: Couldn't find any package by glob 'php7.4-gd'
E: Unable to locate package php7.4-mysql
E: Couldn't find any package by glob 'php7.4-mysql'
./installation-ubuntu-20.04.sh: 35: mysql: not found
./installation-ubuntu-20.04.sh: 36: mysql: not found
./installation-ubuntu-20.04.sh: 37: mysql: not found
./installation-ubuntu-20.04.sh: 40: cd: can't cd to /var/www

**Comment by soapster** [comment]
Fresh install. After apt update.

**Comment by ssddanbrown** [comment]
Hi @soapster,
You seem to be running the wrong script.
You've downloaded, and are running, the Ubuntu 20.04 install script, but from your log output above it seems like you are running Ubuntu 22.04.

**Comment by soapster** [comment]
OMG. I did this before bed. Being a space-case. Sorry about that.
